### PR TITLE
OCaml 4.08.1 migration

### LINKED ISSUE #74: Migrate off camlp4
Camlp4 release for OCaml 4.08 is the last release ever - see the [official announcement](https://discuss.ocaml.org/t/the-end-of-camlp4/4216). It is recommended to port the code to use ppx (extension points), or any external parser (like mehrir, sedlex, ocamllex, ansgtrom, etc).

### PR DESCRIPTION
**Pull request by darrenldl**
Some notable changes
- Migration to dune
- Switched to use of ppx for sexp related functions
- Switching from presumably ocamlyacc to menhir for `parser_yacc.mly` (modified file a bit to fit menhir’s syntax)

Also [migrated Dlist](https://github.com/darrenldl/Dlist) to dune and added files here and there, may be required for this version of Batsh to build

Thanks @XVilka for providing the opam file - added you to the contributor list as well

**EDIT**: Fixes #74

### CODE REVIEW

**Comment by XVilka** [comment]
It will fix also the https://github.com/BYVoid/Batsh/issues/74

**Comment by darrenldl** [comment]
Updated original message to reflect that. Thanks!

**Comment by XVilka** [comment]
It also depends on https://github.com/BYVoid/Dlist/pull/3
Since dlist is released in opam - https://opam.ocaml.org/packages/dlist/ it would be nice to push the new version in opam too @BYVoid

**Comment by XVilka** [comment]
@BYVoid ping? Could you please take a look?

**Comment by darrenldl** [comment]
Superseded by #76 , closing.

**Pull request closed without merging**
